# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
sensor: !include sensors.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
binary_sensor: !include binary_sensors.yaml

# Zigbee Configuration

zha:
  device_config:
    a4:c1:38:86:43:bd:28:92-1:
      type: "switch"

# Ring test
homeassistant:
  allowlist_external_dirs:
    - "/config/tmp"

  # …your other HA settings (name, latitude, unit_system, etc.)
  packages: !include_dir_named packages

# Enable WOL
wake_on_lan:

#Notification Group

notify:
  - name: ALL_NOTI_DEVICES
    platform: group
    services:
      - service: mobile_app_eddies_iphone_17_pm
      - service: mobile_app_janets_iphone_17_pm

  - name: EDDIES_PHONE
    platform: group
    services:
      - service: mobile_app_eddies_iphone_17_pm

  - name: JANETS_PHONE
    platform: group
    services:
      - service: mobile_app_janets_iphone_17_pm

  - platform: file
    name: audit_file
    filename: /config/www/logs/light_on_audit.txt
    timestamp: true

  - platform: file
    name: entity_list_notify
    filename: /config/entities_list.txt # Adjust path as needed
    timestamp: false

#ENABLE STREAM

#ffmpeg:

stream:

# Maria .DB

recorder:
  db_url: mysql://homeassistant:Shipgang25131664!@core-mariadb/homeassistant?charset=utf8mb4

# Family Group

group:
  family:
    icon: mdi:home-heart
    name: family
    entities:
      - person.edward_steele
      - person.janet_steele
      - person.timmy_steele

# Supervisor

panel_custom:
  - name: Supervisor
    url_path: hassio/system
    sidebar_title: Supervisor
    sidebar_icon: mdi:home-assistant
    module_url: /local/panel-redirect.js

#Media Players

###EMBY###

media_player:
  - platform: emby
    host: 172.25.13.235
    port: 8096
    ssl: False
    api_key: c0600f8bc413428085b615164a9b0b76
    

#   - platform: denon
#     host: 172.25.13.55

####JBL Shell CMDS

shell_command:
  # Step 1: Handshake - Always send this first after Home Assistant restarts

  ma510_init: 'printf "\x23\x50\x01\xF0\x0D" | nc 172.25.13.168 50000'

  # Power On / Off

  ma510_power_on: 'printf "\x23\x00\x01\x01\x0D" | nc 172.25.13.168 50000'
  ma510_power_off: 'printf "\x23\x00\x01\x00\x0D" | nc 172.25.13.168 50000'

  # Volume Set to 40 (you can adjust this — 0x00 to 0x63 = volume 0–99)

  ma510_volume_40: 'printf "\x23\x06\x01\x28\x0D" | nc 172.25.13.168 50000'
  ma510_volume_25: 'printf "\x23\x06\x01\x19\x0D" | nc 172.25.13.168 50000'
  ma510_volume_20: 'printf "\x23\x06\x01\x14\x0D" | nc 172.25.13.168 50000'
  ma510_volume_35: 'printf "\x23\x06\x01\x26\x0D" | nc 172.25.13.168 50000'
  ma510_volume_30: 'printf "\x23\x06\x01\x22\x0D" | nc 172.25.13.168 50000'
  ma510_volume_46: 'printf "\x23\x06\x01\x2E\x0D" | nc 172.25.13.168 50000'
  ma510_volume_41: 'printf "\x23\x06\x01\x29\x0D" | nc 172.25.13.168 50000'

  # Mute On / Off

  ma510_mute_on: 'printf "\x23\x07\x01\x01\x0D" | nc 172.25.13.168 50000'
  ma510_mute_off: 'printf "\x23\x07\x01\x00\x0D" | nc 172.25.13.168 50000'

  # Input Selection

  ma510_input_tv: 'printf "\x23\x05\x01\x01\x0D" | nc 172.25.13.168 50000'
  ma510_input_media: 'printf "\x23\x05\x01\x09\x0D" | nc 172.25.13.168 50000'

  # Find Roku Remotes

  roku_find_remote_living_room: 'curl -d "" http://172.25.13.201:8060/keypress/FindRemote'
  roku_find_remote_master: 'curl -d "" http://172.25.13.99:8060/keypress/FindRemote'
  
  # Run Roomba script
  ##update_roomba_pmapv: /root/update_roomba_pmapv.sh
  update_roomba_pmapv: "ssh -i /config/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=10 root@172.25.14.50 'pct exec 100 -- nohup /root/update_roomba_pmapv.sh > /root/roomba_pmapv.log 2>&1 &'"
  
rest_command:
  reolink_front_push_off:
    url: "http://172.25.16.175/cgi-bin/api.cgi"
    method: POST
    username: !secret reolink_front_user
    password: !secret reolink_front_password
    headers:
      Content-Type: application/json
    payload: >
      [{"cmd":"SetPush","action":1,"param":{"Push":{"enable":0}}}]

  reolink_front_push_on:
    url: "http://172.25.16.175/cgi-bin/api.cgi"
    method: POST
    username: !secret reolink_front_user
    password: !secret reolink_front_password
    headers:
      Content-Type: application/json
    payload: >
      [{"cmd":"SetPush","action":1,"param":{"Push":{"enable":1}}}]
      
