substitutions:
  name: everything-presence-lite-936d8c
  friendly_name: Everything Presence Lite (master)
packages:
  EverythingSmartTechnology.Everything Presence Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: LqcelwiUx01yr6TtWfQ81qIM8IrtdaTX/gGbsRpQ/98=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
