substitutions:
  name: everything-presence-one-8f474c
  friendly_name: Everything Presence One (kitchen)
packages:
  Everything Smart Technology.Everything Presence One: github://everythingsmarthome/everything-presence-one/everything-presence-one-sen0609-ble-rev1.6.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: WSBn7JiAzAJv4rrUCzuP75MH+5IiyxlHtWpioUIIww4=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
