homeassistant:
  enabled: true
  experimental_event_entities: true
  legacy_action_sensor: true
advanced:
  network_key:
    - 54
    - 212
    - 157
    - 115
    - 230
    - 121
    - 26
    - 31
    - 66
    - 22
    - 213
    - 49
    - 138
    - 211
    - 151
    - 235
  pan_id: 25313
  ext_pan_id:
    - 197
    - 152
    - 212
    - 186
    - 7
    - 141
    - 175
    - 66
  log_level: info
  channel: 25
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt-user2
  password: mqttuser2
  port: 8099
device_options: {}
devices:
  '0x00158d000af2af29':
    friendly_name: Garage Door Opener(master)
    icon: device_icons/8a6e32e6447964fb879458a4c207d6f6.png
  '0x00158d000af29cc0':
    friendly_name: Garage Door Opener (kitchen)
    icon: device_icons/8a6e32e6447964fb879458a4c207d6f6.png
  '0x00158d000ae4c796':
    friendly_name: 'PLUG: JBL MA 510 Energy Monitor'
    icon: device_icons/ca4646e06588a7dd65eaf0fdc9537452.png
  '0x282c02bfffea87df':
    friendly_name: 'Motion Sensor Make Up '
    icon: device_icons/10db0204819b54c4922afb7ea11aa833.png
  '0x54ef441000c1437e':
    friendly_name: Switch Bathroom
    icon: device_icons/66d04ad933c3368259abc37714f6bfb8.png
  '0x54ef441000a62632':
    friendly_name: Switch Kitchen
    icon: device_icons/66d04ad933c3368259abc37714f6bfb8.png
  '0x282c02bfffea7bf4':
    friendly_name: Motion Sensor Kitchen
    icon: device_icons/10db0204819b54c4922afb7ea11aa833.png
  '0x001788010d8258e8':
    friendly_name: Light Closet 2
    icon: device_icons/64d84384a45563ace1c8201232a46b18.png
  '0x001788010de9af2f':
    friendly_name: Light Lamp
    icon: device_icons/0296ff5a35b83ec81c71b95dc0b86698.png
  '0x001788010d82560a':
    friendly_name: Light Closet 1
    icon: device_icons/64d84384a45563ace1c8201232a46b18.png
  '0x00158d008afe14ce':
    friendly_name: Temp/Humidity Sensor (office)
    icon: device_icons/8da97afa2d57d9d2e86756a4aa2a6072.png
  '0x54ef441000c140fa':
    friendly_name: Switch Dining Room
    icon: device_icons/66d04ad933c3368259abc37714f6bfb8.png
  '0x001788010cce8600':
    friendly_name: Light Closet 3
    icon: device_icons/64d84384a45563ace1c8201232a46b18.png
  '0x001788010d58db09':
    friendly_name: Light Kitchen Porch
    icon: device_icons/ba5819cfccc6fa812112277d94ecdf9f.png
  '0x00158d000af1fb01':
    friendly_name: Temp/Humidity Sensor (master)
    icon: device_icons/8da97afa2d57d9d2e86756a4aa2a6072.png
  '0x00158d008afe1557':
    friendly_name: Temp/Humidity Sensor (living)
    icon: device_icons/8da97afa2d57d9d2e86756a4aa2a6072.png
  '0x00158d000af1d167':
    friendly_name: Temp/Humidity Sensor (network rack)
    icon: device_icons/8da97afa2d57d9d2e86756a4aa2a6072.png
  '0x54ef4410009410c9':
    friendly_name: Switch Closet
    icon: device_icons/66d04ad933c3368259abc37714f6bfb8.png
  '0x54ef441000c14385':
    friendly_name: Switch Master Bedroom Door
    icon: device_icons/66d04ad933c3368259abc37714f6bfb8.png
  '0x001788010de9bab9':
    friendly_name: 'Light Hue Front porch '
    icon: device_icons/0296ff5a35b83ec81c71b95dc0b86698.png
  '0x001788010d941fa1':
    friendly_name: Light Hue Back Driveway
    icon: device_icons/fe9e51968dfe053cf2b683964b246d37.png
  '0xa4c138f58ed785a9':
    friendly_name: Tundra Alarm Zigbee
    icon: device_icons/d2983fba8d258cc39bb7d3898fadbd33.png
  '0x881a14fffe4212dc':
    friendly_name: Living Room Fan
    icon: device_icons/942c200ede0fa3db51ce28dedbabeae5.png
  '0x00158d000af2ca9d':
    friendly_name: Garage Door opener(garage)
    icon: device_icons/8a6e32e6447964fb879458a4c207d6f6.png
  '0x001788010e2f121a':
    friendly_name: 'Bathroom Under Cabinet '
    icon: device_icons/cc70af6438ff313d1bafd671e7bd2921.png
  '0x001788010e2f1299':
    friendly_name: Under TV Cabinet
    icon: device_icons/cc70af6438ff313d1bafd671e7bd2921.png
  '0x282c02bfffec2e16':
    friendly_name: 'PLUG: Christmas Window Lights '
    icon: device_icons/071eda40e14d3ba37057472c0c9786d4.png
  '0x001788010e1bc4f2':
    friendly_name: Dining Room 1
    icon: device_icons/f3d1aebd1ed9ef9b5887a516ab6e776a.png
  '0x001788010e1bc3d5':
    friendly_name: Dining Room 2
    icon: device_icons/f3d1aebd1ed9ef9b5887a516ab6e776a.png
  '0x001788010e1b5e31':
    friendly_name: Dining Room 3
    icon: device_icons/f3d1aebd1ed9ef9b5887a516ab6e776a.png
  '0xa4c138a3dbf2e16d':
    friendly_name: 'Office Power Strip '
    icon: device_icons/9ee50e26d4106bfff39e75e8ab172c76.png
  '0x282c02bfffea87eb':
    friendly_name: Garage Motion Sensor TR
    icon: device_icons/10db0204819b54c4922afb7ea11aa833.png
  '0x00158d000ad629ce':
    friendly_name: FlashForge Aqara Button
    icon: device_icons/8a6e32e6447964fb879458a4c207d6f6.png
  '0xa4c1382da018d8ca':
    friendly_name: Linen Closet Light
    icon: device_icons/9e835f5bc5f48cf6cdacd28ee3746196.png
  '0x00158d008afe1551':
    friendly_name: Temp/Humidity Sensor (kitchen)
    icon: device_icons/8da97afa2d57d9d2e86756a4aa2a6072.png
  '0x00158d000af1f50e':
    friendly_name: Temp/Humidity Sensor (bathroom)
    icon: device_icons/8da97afa2d57d9d2e86756a4aa2a6072.png
  '0x54ef441000c64199':
    friendly_name: Aqara Motion (office)
    icon: device_icons/e3cf8f26cf8676dbe6b7cafc07a77acf.png
  '0x54ef441000a443af':
    friendly_name: Aqara Motion (hallway)
    icon: device_icons/e3cf8f26cf8676dbe6b7cafc07a77acf.png
  '0x54ef441000a42bdf':
    friendly_name: Aqara Motion (bathroom)
    icon: device_icons/e3cf8f26cf8676dbe6b7cafc07a77acf.png
  '0x54ef441000c7c7e8':
    friendly_name: Aqara Motion (closet)
    icon: device_icons/e3cf8f26cf8676dbe6b7cafc07a77acf.png
  '0x001788010cb76828':
    friendly_name: Office Hue Orb Left
    icon: device_icons/cc11dea919c4afbafc121d0f43f24bcc.png
  '0x001788010d1a24f1':
    friendly_name: Office Hue Orb Right
    icon: device_icons/cc11dea919c4afbafc121d0f43f24bcc.png
  '0x54ef441000d7b10e':
    friendly_name: hallway light
    icon: device_icons/74cbcd34e6bc7ad7b91afa59213e2923.png
  '0x0ceff6fffe59fa5b':
    friendly_name: Sonoff Master Temp/Hum Sensor
    icon: device_icons/d5cf7e365fed2168925ab63b5dfd83e6.png
  '0x282c02bfffec60c8':
    friendly_name: 'PLUG: Network Rack Fans '
    icon: device_icons/071eda40e14d3ba37057472c0c9786d4.png
  '0x0ceff6fffe400692':
    friendly_name: Temp/Humidity Sensor sonoff (bathroom)
  '0x001788010f47b3f5':
    friendly_name: Master Bedroom Light Main
  '0x001788010f47b3ff':
    friendly_name: Master Bedroom Light Top
  '0x00158d008bb47557':
    friendly_name: 'LEAK SENSOR: Home Bathroom'
  '0x00158d008bb5a82c':
    friendly_name: 'LEAK SENSOR: Garage Bathroom'
  '0x282c02bfffec2808':
    friendly_name: Christmas Tree Lights
  '0x282c02bfffec27ac':
    friendly_name: 'PLUG: denon reset'
  '0x54ef44100156338d':
    friendly_name: Switch Master Bedroom Main
  '0x001788010eb76b0a':
    friendly_name: Janets Light Left
  '0x001788010eb76084':
    friendly_name: Janets Light Right
blocklist:
  - '0x282c02bfffe3e034'
serial:
  port: tcp://Dongle-M.local:6638
  adapter: ember
  baudrate: 11500
adapter: ember
frontend:
  enabled: true
  port: 8099
version: 4
groups:
  '1':
    friendly_name: dining_room_lights_z2m_group
    filtered_attributes: []
  '2':
    friendly_name: Master Bedroom Light z2m Group
  '3':
    friendly_name: Janest Light z2m Group
    filtered_attributes: []
  '4':
    friendly_name: hue_closet_lights_group
